CREATE TABLE IF NOT EXISTS accounts.accounts (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_id varchar(250),
	account_code varchar(250),
	name varchar,
	type varchar(250),
	bank_account_number varchar(250),
	status varchar(50),
	description varchar,
	bank_account_type varchar(50),
	currency_code varchar(10),
	tax_type varchar(250),
	enable_payments_to_account int,
	show_in_expense_claims int,
	property_class varchar(50),
	system_account varchar(50),
	reporting_code varchar(250),
	reporting_code_name varchar(250),
	has_attachments int,
	updated_date_utc timestamp,
	add_to_watch_list int
);

create index IF NOT EXISTS accounts_id_indx on accounts.accounts (account_id);

