CREATE TABLE IF NOT EXISTS invoices.payments (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	payment_id varchar(250),
	invoice_id varchar(250),
	credit_note text,
	prepament text,
	overpayment text,
	invoice_number varchar(250),
	credit_note_number varchar(250),
	account_id varchar(250),
	code varchar(250),
	payment_date date,
	currency_rate decimal,
	amount decimal,
  reference varchar(250),
  isReconciled int,
  status varchar(250),
  payment_type varchar(250),
  updated_date_utc timestamp,
  bank_account_number varchar(250),
  particulars varchar(250),
  details varchar(250),
  has_account int
);

create index IF NOT EXISTS payment_id_indx on invoices.payments (payment_id);

