CREATE TABLE IF NOT EXISTS bank_transactions.bank_accounts (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bank_account_id varchar(250),
	name varchar,
	code varchar(250)
);

create index IF NOT EXISTS bank_account_id_indx on bank_transactions.bank_accounts (bank_account_id);
