CREATE TABLE IF NOT EXISTS bank_transactions.line_items (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	line_item_id varchar(250),
	bank_transaction_id varchar(250),
	description text,
	quantity decimal,
	unit_amount decimal,
	item_code varchar(250),
	account_code varchar(250),
	tax_type varchar(250),
	tax_amount decimal,
	line_amount decimal,
	tracking text,
	discount_rate decimal,
	discount_amount decimal,
	repeating_invoice_id varchar(250)
);

create index IF NOT EXISTS line_items_bank_transaction_id_indx on bank_transactions.line_items (bank_transaction_id);
