CREATE TABLE bank_accounts (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bank_account_id varchar(250),
	name varchar(1000),
	code varchar(250)
);

create index bank_account_id_indx on bank_accounts (bank_account_id);
